--
-- PostgreSQL database dump
--

\restrict LYg8vaGjOChqHzzm3iHpjpbmzA8Ig1kN2KJjZAPNNBh6xpwIUAe73BLkpZ4AIWD

-- Dumped from database version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: proposicoes_legislativas; Type: TABLE; Schema: public; Owner: kaua
--

CREATE TABLE public.proposicoes_legislativas (
    id integer NOT NULL,
    numero integer NOT NULL,
    tipo character varying(10) NOT NULL,
    ano integer NOT NULL,
    data_apresentacao timestamp without time zone,
    ementa_resumo text,
    artigo_1_trecho text,
    link_pdf text,
    CONSTRAINT proposicoes_legislativas_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PL'::character varying, 'PEC'::character varying, 'MPV'::character varying])::text[])))
);


ALTER TABLE public.proposicoes_legislativas OWNER TO kaua;

--
-- Name: TABLE proposicoes_legislativas; Type: COMMENT; Schema: public; Owner: kaua
--

COMMENT ON TABLE public.proposicoes_legislativas IS 'Repositório de Projetos de Lei (PL), Emendas Constitucionais (PEC) e Medidas Provisórias (MPV) de 2024';


--
-- Name: COLUMN proposicoes_legislativas.numero; Type: COMMENT; Schema: public; Owner: kaua
--

COMMENT ON COLUMN public.proposicoes_legislativas.numero IS 'Número da proposição legislativa';


--
-- Name: COLUMN proposicoes_legislativas.tipo; Type: COMMENT; Schema: public; Owner: kaua
--

COMMENT ON COLUMN public.proposicoes_legislativas.tipo IS 'Tipo da proposição: PL, PEC ou MPV';


--
-- Name: COLUMN proposicoes_legislativas.ano; Type: COMMENT; Schema: public; Owner: kaua
--

COMMENT ON COLUMN public.proposicoes_legislativas.ano IS 'Ano da proposição';


--
-- Name: COLUMN proposicoes_legislativas.data_apresentacao; Type: COMMENT; Schema: public; Owner: kaua
--

COMMENT ON COLUMN public.proposicoes_legislativas.data_apresentacao IS 'Data e hora de apresentação da proposição';


--
-- Name: COLUMN proposicoes_legislativas.ementa_resumo; Type: COMMENT; Schema: public; Owner: kaua
--

COMMENT ON COLUMN public.proposicoes_legislativas.ementa_resumo IS 'Ementa ou resumo da proposição';


--
-- Name: COLUMN proposicoes_legislativas.artigo_1_trecho; Type: COMMENT; Schema: public; Owner: kaua
--

COMMENT ON COLUMN public.proposicoes_legislativas.artigo_1_trecho IS 'Trecho do Artigo 1º da proposição';


--
-- Name: COLUMN proposicoes_legislativas.link_pdf; Type: COMMENT; Schema: public; Owner: kaua
--

COMMENT ON COLUMN public.proposicoes_legislativas.link_pdf IS 'Link para o PDF da proposição no site da Câmara';


--
-- Name: proposicoes_legislativas_id_seq; Type: SEQUENCE; Schema: public; Owner: kaua
--

CREATE SEQUENCE public.proposicoes_legislativas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.proposicoes_legislativas_id_seq OWNER TO kaua;

--
-- Name: proposicoes_legislativas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: kaua
--

ALTER SEQUENCE public.proposicoes_legislativas_id_seq OWNED BY public.proposicoes_legislativas.id;


--
-- Name: proposicoes_legislativas id; Type: DEFAULT; Schema: public; Owner: kaua
--

ALTER TABLE ONLY public.proposicoes_legislativas ALTER COLUMN id SET DEFAULT nextval('public.proposicoes_legislativas_id_seq'::regclass);


--
-- Data for Name: proposicoes_legislativas; Type: TABLE DATA; Schema: public; Owner: kaua
--

COPY public.proposicoes_legislativas (id, numero, tipo, ano, data_apresentacao, ementa_resumo, artigo_1_trecho, link_pdf) FROM stdin;
1	295	PL	2024	2025-11-04 20:40:00	Altera o Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), para prever o processamento mediante ação penal pública incondicionada para o crime de dano em contexto de violência doméstica contra a mulher.	Art. 1º O art. 167 do Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), passa a vigorar acrescido do seguinte parágrafo único: “Art. 167. Parágrafo único. Nos casos do caput e do inciso IV do parágrafo único, ambos do art. 163 deste Código, se procederá mediante ação pública incondicionada quando praticados em contexto de violência doméstica, observado o disposto no inciso IV do art. 7º da Lei nº 11.340, de 7 de agosto de 2006 (Lei Maria da Penha).” (NR) Art. 2º Esta Lei entra em vigor na data de sua publicação. Brasília, na data da assinatura.	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=3040003
2	3600	PL	2024	2025-10-27 09:51:00	Altera a Lei nº 9.394, de 20 de dezembro de 1996 (Lei de Diretrizes e Bases da Educação Nacional), e a Lei nº 14.645, de 2 de agosto de 2023, para considerar os povos indígenas e quilombolas na oferta de educação profissional e tecnológica.	Art. 1º O art. 42-B da Lei nº 9.394, de 20 de dezembro de 1996 (Lei de Diretrizes e Bases da Educação Nacional), passa a vigorar acrescido do seguinte parágrafo único: “Art. 42- B. Parágrafo único. Inclui-se no contexto social referido no caput deste artigo a consideração dos saberes dos povos indígenas e quilombolas.” (NR) Art. 2º O inciso I do caput do art. 4º da Lei nº 14.645, de 2 de agosto de 2023, passa a vigorar com a seguinte redação:	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=3029891
3	425	PL	2024	2025-10-23 20:30:00	Altera o Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), para aumentar a pena do crime de favorecimento da prostituição ou de outra forma de exploração sexual de criança ou adolescente ou de vulnerável.	Art. 1º O art. 218-B do Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), passa a vigorar com a seguinte redação: “Art. 218- B. Pena – reclusão, de 6 (seis) a 12 (doze) anos. ” (NR) Art. 2º Esta Lei entra em vigor na data de sua publicação. Brasília, na data da assinatura. Senador Davi Alcolumbre Presidente do Senado Federal	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=3029597
4	4809	PL	2024	2025-10-23 20:30:00	Altera o Decreto-Lei nº 3.689, de 3 de outubro de 1941 (Código de Processo Penal); o Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal); a Lei nº 10.826, de 22 de dezembro de 2003 (Estatuto do Desarmamento); a Lei nº 8.072, de 25 de julho de 1990 (Lei dos Crimes Hediondos); e a Lei nº 11.343, de 23 de agosto de 2006 (Lei de Drogas), para endurecer a resposta penal aos crimes cometidos com violência.	Art. 1º O art. 312 do Decreto-Lei nº 3.689, de 3 de outubro de 1941 (Código de Processo Penal), passa a vigorar com a seguinte redação: “Art. 312. § 3º Devem ser considerados na aferição da periculosidade do agente, geradora de riscos à ordem pública: I – o modus operandi, inclusive quanto ao uso reiterado de violência ou grave ameaça à pessoa; II – a participação em organização criminosa ou milícia privada; III – a natureza, a quantidade e a variedade de drogas, armas ou	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=3029568
5	1271	PL	2024	2025-10-14 15:59:00	Altera a Consolidação das Leis do Trabalho, aprovada pelo Decreto-Lei nº 5.452, de 1º de maio de 1943, para ampliar a quantidade de dias que o empregado poderá deixar de comparecer ao serviço sem prejuízo do salário, em caso de falecimento de cônjuge, companheiro, pais, madrasta ou padrasto, filhos, enteados, menor sob guarda ou tutela e irmãos.	Art. 1º O inciso I do caput do art. 473 da Consolidação das Leis do Trabalho, aprovada pelo Decreto-Lei nº 5.452, de 1º de maio de 1943, passa a vigorar com a seguinte redação: “Art. 473. I – até 8 (oito) dias consecutivos, em caso de falecimento de cônjuge, companheiro, pais, madrasta ou padrasto, filhos, enteados, menor sob guarda ou tutela e irmãos e, até 2 (dois) dias consecutivos, em caso de falecimento de pessoa não mencionada anteriormente, que seja seu ascendente, descendente ou que, declarada em sua carteira de trabalho e previdência social, viva sob sua dependência econômica;	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=3022646
6	2895	PL	2024	2025-10-14 15:41:00	Inscreve o nome de Frei Antônio de Sant’Anna Galvão, o Frei Galvão, no Livro dos Heróis e Heroínas da Pátria.	Art. 1º Inscreva-se o nome de Frei Antônio de Sant’Anna Galvão, o Frei Galvão, no Livro dos Heróis e Heroínas da Pátria, depositado no Panteão da Pátria e da Liberdade Tancredo Neves, em Brasília. Art. 2º Esta Lei entra em vigor na data de sua publicação. Brasília, na data da assinatura. Senador Davi Alcolumbre Presidente do Senado Federal gsl/pl24-2895rev-t aseM -	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=3022613
7	680	PL	2024	2025-10-14 15:27:00	Altera a Lei nº 12.468, de 26 de agosto de 2011, para dispor sobre transferência de titularidade de outorgas concedidas a profissionais taxistas.	Art. 1º Esta Lei altera a Lei nº 12.468, de 26 de agosto de 2011, para dispor sobre a transferência de titularidade de outorgas concedidas a profissionais taxistas. Art. 2º A Lei nº 12.468, de 26 de agosto de 2011, passa a vigorar com as seguintes alterações: “Art. 5º VI – não descontinuar a prestação do serviço de táxi injustificadamente ou sem autorização expressa do poder público outorgante.” (NR) “Art. 16. A cessão de direitos decorrentes da outorga concedida para	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=3022608
8	3259	PL	2024	2025-10-02 18:06:00	Reconhece o grupo folclórico Parafusos de Lagarto como manifestação da cultura nacional.	Art. 1º É reconhecido como manifestação da cultura nacional o grupo folclórico Parafusos de Lagarto. Art. 2º Esta Lei entra em vigor na data de sua publicação. Brasília, na data da assinatura. Senador Davi Alcolumbre Presidente do Senado Federal Hall/pl24-3259 aseM - 381.12:60:81	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=3013051
9	2932	PL	2024	2025-10-02 17:48:00	Institui a Rota Turística dos Lençóis Maranhenses e do Delta, no Estado do Maranhão.	Art. 1º É instituída a Rota Turística dos Lençóis Maranhenses e do Delta, compreendendo os Municípios de Barreirinhas, Humberto de Campos, Paulino Neves, Primeira Cruz, Santo Amaro do Maranhão, Araioses, Água Doce do Maranhão, Urbano Santos e Tutóia, no Estado do Maranhão. Art. 2º A Rota Turística dos Lençóis Maranhenses e do Delta tem os seguintes objetivos: I – desenvolver o potencial turístico regional e local; II – fomentar o empreendedorismo e a inovação das atividades turísticas; III – fortalecer e fomentar os setores ligados ao turismo; IV – promover o crescimento econômico local, sustentável e inclusivo;	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=3013029
10	1086	PL	2024	2025-09-11 15:25:00	Altera a Lei nº 14.133, de 1º de abril de 2021 (Lei de Licitações e Contratos Administrativos), para estabelecer margem de preferência nas aquisições de bens compostáveis ou eficientes no uso de energia, água ou materiais, e de bens e serviços que atendam a critérios de sustentabilidade, e dá outras providências.	Art. 1º Esta Lei estabelece margem de preferência nas aquisições de bens compostáveis ou eficientes no uso de energia, água ou materiais, e de bens e serviços que atendam a critérios de sustentabilidade, conforme regulamento, e aperfeiçoa a definição do catálogo eletrônico de padronização de compras, serviços e obras. Art. 2º A Lei nº 14.133, de 1º de abril de 2021 (Lei de Licitações e Contratos Administrativos), passa a vigorar com as seguintes alterações: “Art. 6º LI – catálogo eletrônico de padronização de compras, serviços e obras: sistema de gerenciamento centralizado, destinado a permitir a padronização	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2999988
11	3021	PL	2024	2025-09-03 14:00:00	Altera a Lei nº 11.664, de 29 de abril de 2008, e a Lei nº 9.656, de 3 de junho de 1998 (Lei dos Planos de Saúde), para garantir a realização de exames mamográficos sem limitação de quantidade e periodicidade.	Art. 1º O art. 2º da Lei nº 11.664, de 29 de abril de 2008, passa a vigorar acrescido do seguinte § 4º: “Art. 2º § 4º No que se refere ao rastreamento do câncer de mama, o exame de mamografia, referido no inciso II do caput deste artigo, será assegurado, sem limitação de quantidade e periodicidade, a todas as mulheres a partir dos 30 (trinta) anos consideradas de alto risco, portadoras de mutação genética ou com forte história familiar de câncer de mama ou ovário, ou, ainda, com risco maior ou igual a 20% (vinte por cento) ao longo da vida,	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2992496
12	3611	PL	2024	2025-09-02 18:34:00	Altera a Lei nº 9.394, de 20 de dezembro de 1996 (Lei de Diretrizes e Bases da Educação Nacional), para dispor sobre condições de igualdade na prestação de serviços educacionais por instituições de ensino privadas a estudantes bolsistas.	Art. 1º O art. 3º da Lei nº 9.394, de 20 de dezembro de 1996 (Lei de Diretrizes e Bases da Educação Nacional), passa a vigorar com a seguinte redação: “Art. 3º § 1º Como decorrência do princípio da igualdade de condições para o acesso e permanência na escola, as instituições de ensino privadas que ofereçam bolsas de estudos deverão garantir o desenvolvimento de política de bolsas inclusiva, com igualdade de condições entre os estudantes bolsistas e não bolsistas, e implementar mecanismos que visem à integração dos educandos e à superação de estigmas.	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2992221
13	2936	PL	2024	2025-08-12 18:48:00	Reconhece a Dança de São Gonçalo como manifestação da cultura nacional.	Art. 1º É reconhecida como manifestação da cultura nacional a Dança de São Gonçalo. Art. 2º Esta Lei entra em vigor na data de sua publicação. Brasília, na data da assinatura. Senador Davi Alcolumbre Presidente do Senado Federal phfm/pl24-2936 aseM - 756.53:84:81	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2971679
14	3603	PL	2024	2025-08-12 18:48:00	Institui o Dia Nacional do Cidadão Solidário.	Art. 1º É instituído o Dia Nacional do Cidadão Solidário, a ser celebrado, anualmente, no primeiro dia do prazo de entrega da Declaração de Ajuste Anual do Imposto sobre a Renda das Pessoas Físicas. Parágrafo único. Na semana que anteceder o Dia Nacional do Cidadão Solidário deverão ser realizadas atividades voltadas à conscientização sobre o tema. Art. 2º Esta Lei entra em vigor na data de sua publicação. Brasília, na data da assinatura. Senador Davi Alcolumbre Presidente do Senado Federal phfm/pl24-3603	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2971675
15	2938	PL	2024	2025-07-18 15:03:00	Reconhece a Chegança como manifestação da cultura nacional.	Art. 1º É reconhecida a Chegança como manifestação da cultura nacional. Art. 2º Esta Lei entra em vigor na data de sua publicação. Brasília, 18 de julho de 2025. Senador Davi Alcolumbre Presidente do Senado Federal gsl/pl24-2938rev-t aseM - 044.11:30:51 5202/70/81	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2960850
16	4799	PL	2024	2025-07-18 14:58:00	Institui a Semana Nacional de Educação Cidadã.	Art. 1º É instituída a Semana Nacional de Educação Cidadã, a ser realizada, anualmente, na segunda semana de agosto. Art. 2º A Semana Nacional de Educação Cidadã integrará o calendário nacional e terá o objetivo de fomentar, promover e reconhecer o papel da educação cidadã na formação de uma sociedade consciente e participativa. Art. 3º Os objetivos da Semana Nacional de Educação Cidadã estão abarcados pelas seguintes diretrizes, sempre obedecendo ao suprapartidarismo e ao desenvolvimento da consciência crítica como princípio pedagógico: I – incentivo à educação cidadã e ao exercício da cidadania; II – apoio ao letramento político como educação para a democracia;	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2960839
17	1884	PL	2024	2025-07-07 14:41:00	Regulamenta o exercício das profissões de instrutor de voo livre e de piloto de voo duplo turístico de aventura.	Art. 1º Esta Lei regulamenta o exercício profissional dos instrutores de voo livre e dos pilotos de voo duplo turístico de aventura, dispondo sobre as atribuições, as competências e os requisitos exigidos para a prática dessas atividades, em todo o território nacional. Art. 2º É instrutor de voo livre o profissional dedicado à formação de aerodesportistas, com registro na Confederação Brasileira de Voo Livre (CBVL), entidade responsável pela formação de pilotos de aeronaves experimentais, tais como ultraleves, parapentes e asas voadoras (asas-delta), não propulsadas, e na Federação Aeronáutica Internacional (FAI), devendo possuir cadastro de aerodesportista emitido pela Agência Nacional de Aviação Civil (Anac), conforme o Regulamento Brasileiro de Aviação Civil	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2950032
18	3069	PL	2024	2025-07-07 14:25:00	Denomina “Rodovia Antão Luiz de Melo” o trecho entre o km 42,9 e o km 53,7 da rodovia BR-232, no Município de Vitória de Santo Antão, no Estado de Pernambuco.	Art. 1º É denominada “Rodovia Antão Luiz de Melo” o trecho entre o km 42,9 e o km 53,7 da rodovia BR-232, no Município de Vitória de Santo Antão, no Estado de Pernambuco. Art. 2º Esta Lei entra em vigor na data de sua publicação. Brasília, na data da assinatura. Senador Davi Alcolumbre Presidente do Senado Federal gsl/pl24-3069rev-t aseM -	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2950018
19	2800	PL	2024	2025-07-07 14:20:00	Cria a Rota Cênica da Estrada Velha de Urupema, no Estado de Santa Catarina.	Art. 1º Esta Lei cria a Rota Cênica da Estrada Velha de Urupema, no Estado de Santa Catarina. Art. 2º São objetivos da Rota Cênica da Estrada Velha de Urupema, no Estado de Santa Catarina: I – desenvolver as atividades turísticas em sua região; II – promover um modelo de desenvolvimento econômico sustentável para o território e seus habitantes; III – fomentar o empreendedorismo e a inovação nas atividades turísticas; IV – valorizar os atrativos naturais, culturais e históricos da região. Art. 3º A estruturação, a gestão e a promoção dos atrativos turísticos	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2950011
20	1533	PL	2024	2025-06-23 17:12:00	Altera a Lei nº 13.257, de 8 de março de 2016 (Marco Legal da Primeira Infância), para criar sistema nacional de informação sobre o desenvolvimento integral da primeira infância.	Art. 1º O art. 11 da Lei nº 13.257, de 8 de março de 2016 (Marco Legal da Primeira Infância), passa a vigorar acrescido dos seguintes §§ 3º e 4º: “Art. 11. § 3º Para atender ao disposto neste artigo, será implementado, em articulação com os entes federados, sistema nacional de informação sobre o desenvolvimento integral da primeira infância, com integração dos bancos de dados das áreas de saúde, educação, assistência social e proteção. § 4º O sistema de que trata o § 3º contará também com informações detalhadas sobre creches e demais instituições de atendimento à primeira	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2940501
21	18	PEC	2024	2025-03-13 19:31:00	Dá nova redação ao § 4º do art. 225 da Constituição Federal para incorporar ao patrimônio nacional o Pantanal Sul-Mato-Grossense.	Art. 1º O § 4º do art. 225 da Constituição Federal passa a vigorar com a seguinte redação: “Art. 255. § 4º A Floresta Amazônica brasileira, a Mata Atlântica, a Serra do Mar, o Pantanal Sul-Mato-Grossense, o Pantanal Mato-Grossense e a Zona Costeira são patrimônio nacional, e sua utilização far-se-á, na forma da lei, dentro de condições que assegurem a preservação do meio ambiente, inclusive quanto ao uso dos recursos naturais. ” (NR)	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2866935
22	51	PEC	2024	2024-12-12 17:45:00	Altera o art. 7º e o Ato das Disposições Constitucionais Transitórias da Constituição Federal de 1988, para dispor sobre as condições especiais de trabalho do motorista profissional empregado no transporte rodoviário de cargas e de passageiros.	Art. 1º O art. 7º da Constituição Federal passa a viger acrescido do seguinte §2º, renomeando-se seu parágrafo único para §1º: “Art.7º §1º §2º Estritamente no caso de atividades de transporte rodoviário de cargas e de passageiros, a lei estabelecerá condições especiais de trabalho do motorista profissional relativas a: I – jornada de trabalho e tempo à disposição do empregador; II – tempo de espera nas atividades de carga e descarga; III – condições de fruição e de fracionamento dos intervalos de	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2841251
23	48	PEC	2024	2024-12-11 10:56:00	Altera o art. 53 da Constituição Federal para deixar explícito que a imunidade material de Deputados e Senadores se aplica independentemente do local em que forem proferidas opiniões, palavras e votos, e para determinar ao Ministro do Supremo Tribunal Federal que, no exercício de suas funções, contrariar esta disposição, a pena de perda do cargo, sem vencimentos e com inabilitação, por até cinco anos, para o exercício de qualquer função pública.	Art. 1º O art. 53 da Constituição Federal passa a vigorar com as seguintes alterações: “Art. 53. Os Deputados e Senadores são invioláveis, civil e penalmente, por quaisquer de suas opiniões, palavras e votos, independentemente do local em que forem proferidos, inclusive em meios de comunicação e aplicações de internet, além de redes sociais. . § 9º O Ministro do Supremo Tribunal Federal que, no exercício	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2838887
24	45	PEC	2024	2024-12-03 07:15:00	Altera os art. 37, art. 163, art. 203, art. 212-A e art. 239 da Constituição e o art. 76 do Ato das Disposições Constitucionais Transitórias - ADCT e acresce os art. 138 e art. 139 ao ADCT.	Art. 1º A Constituição passa a vigorar com as seguintes alterações: “Art. 37. § 11. Somente poderão ser excetuadas dos limites remuneratórios de que trata o inciso XI do caput as parcelas de caráter indenizatório expressamente previstas em lei complementar de caráter nacional aplicada a todos os Poderes e órgãos constitucionalmente autônomos.	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2830980
25	44	PEC	2024	2024-11-26 09:57:00	Altera o §9º do artigo 166 da Constituição Federal para destinar parte dos recursos oriundos das emendas individuais a programas e ações relacionados ao Esporte.	Art. 1º O §9º do art. 166 da Constituição Federal passa a vigorar com a seguinte redação: “Art. 166 § 9º As emendas individuais ao projeto de lei orçamentária serão aprovadas no limite de 2% (dois por cento) da receita corrente líquida do exercício anterior ao do encaminhamento do projeto, observado que a metade desse percentual será destinada a ações e serviços públicos de saúde e 3% (três por cento) a programas e ações relacionados ao esporte.” (NR)	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2825963
26	42	PEC	2024	2024-11-11 09:32:00	Acrescenta o inciso VI ao art. 51 da Constituição Federal, para estabelecer competência privativa à Câmara dos Deputados relativa à fiscalização das atividades das agências reguladoras.	Art. 1º O caput do art. 51 da Constituição Federal passa a vigorar acrescido do seguinte inciso VI: “Art. 51. VI - acompanhar e fiscalizar, por meio de suas comissões, as atividades e atos normativos das agências reguladoras, podendo assinar prazo para a adoção de providências necessárias ao exato cumprimento da lei, sendo eventuais condutas ilícitas dolosas por ação ou omissão encaminhadas ao Ministério Público, à Advocacia-Geral da União e ao Tribunal de Contas da União, para que promovam, conforme suas competências, a	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2817889
27	34	PEC	2024	2024-09-19 13:19:00	Inclui a primeira infância como beneficiária de direitos e garantias, no Texto Constitucional.	Art. 1º A Constituição Federal passa a vigorar com as seguintes alterações: “Art. 227. É dever da família, da sociedade e do Estado assegurar à criança, desde a primeira infância, ao adolescente e ao jovem, com absoluta prioridade, o direito à vida, à saúde, à alimentação, à educação, ao lazer, à profissionalização, à cultura, à dignidade, ao respeito, à liberdade e à convivência familiar e comunitária, além de colocá-los a salvo de toda forma de negligência, discriminação, exploração, violência, crueldade e opressão. § 1º O Estado promoverá programas de assistência integral à saúde	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2478291
28	31	PEC	2024	2024-08-27 18:40:00	Acrescenta os arts.91-A, 91-B e a alínea “g” do inciso I do artigo 159 da Constituição Federal, para instituir o Conselho Nacional de Mudança Climática, a Autoridade Climática Nacional e o Fundo Nacional de Mudança Climática.	Art. 1º A Constituição Federal passa a vigorar acrescida dos seguintes arts. 91- A e 91-B: “Art. 91-A. O Conselho Nacional de Mudança Climática é órgão colegiado da Administração Federal, e dele participam: I – o Presidente da República, que o presidirá, podendo ser substituído nessas funções pelo Vice-Presidente da República; II - o Presidente da Câmara dos Deputados; III - o Presidente do Senado Federal; IV – Ministro de Estado designado pelo Presidente da República; V – três governadores de Estado, eleitos entre si;	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2470429
29	29	PEC	2024	2024-07-10 19:35:00	Altera a Constituição Federal para acrescentar no art. 5º texto sobre o marco temporal de início da vida humana explicitando de forma inequívoca a inviolabilidade do direito à vida, desde a sua concepção, bem como cria o inciso LXXX para especificar que a concepção é a junção do gameta masculino e o feminino, ocorrida durante a fecundação, em local propício para o desenvolvimento celular.	Art. 1º O caput do art. 5º passa a vigorar com as seguintes alterações: “Artigo 5º Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do direito à vida, desde a sua concepção, à liberdade, à igualdade, à segurança e à propriedade, nos termos seguintes: () LXXX – Para efeito do disposto no caput, considera-se concepção a junção entre o gameta masculino e o feminino, ocorrida na	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2453859
30	28	PEC	2024	2024-07-10 18:43:00	Acrescenta o art. 97-A e §§4º e 5º da Constituição Federal de 1988, para estabelecer o julgamento de referendo de liminares pelo colegiado de Tribunal, bem como criar hipótese de sustação de decisão do Supremo Tribunal Federal.	Art. 1º Acrescenta o art. 97-A e §§4º e 5º à Constituição Federal de 1988 e estabelece o julgamento de referendo de liminares pelo colegiado de Tribunal, bem como define hipótese de sustação de decisão do Supremo Tribunal Federal. “Art. 97-A Compete aos relatores de processos em Tribunais submeter imediatamente ao órgão colegiado competente, para referendo, medidas cautelares de natureza cível ou penal necessárias à proteção de direito suscetível de grave dano de incerta reparação, ou ainda destinadas a garantir a eficácia da ulterior decisão da causa. Parágrafo único. A medida cautelar concedida nos termos do caput produzirá efeitos imediatos e será automaticamente inserida na pauta da sessão	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2453821
31	27	PEC	2024	2024-07-08 21:56:00	Altera a Constituição Federal para acrescentar o Capítulo IX - Da Promoção Da Igualdade Racial, que institui o Fundo Nacional de Reparação Econômica e de Promoção da Igualdade Racial (FNREPIR) com o objetivo de promover a igualdade de oportunidades e a inclusão social dos brasileiros pretos e pardos, e dá outras providências	Art. 1º A Constituição Federal passa a vigorar com as seguintes alterações: “CAPÍTULO IX DA PROMOÇÃO DA IGUALDADE RACIAL “Art. 232-A. Fica criado o Fundo Nacional de Reparação Econômica e de Promoção da Igualdade Racial (FNREPIR) com o objetivo de promover a igualdade de oportunidades e a inclusão social da população negra brasileira. § 1º O fundo de que trata esse artigo deverá ser administrado por instituição financeira federal, terá natureza privada, e	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2450923
32	24	PEC	2024	2024-06-24 12:10:00	Altera os §§ 4º, 4°-B e 7º do art. 40 da Constituição Federal e os artigos 5º, 10, 23, 24 e 26 da Emenda Constitucional nº 103, de 2019, acrescenta o art. 144-A a Constituição e dá outras providências.	Art. 1°. Acrescente-se à Constituição Federal o caput do art. 144-A, seguido respectivamente dos §§ 1º e 2º, que passam a vigorar com a seguinte redação: Art. 144-A. Os agentes socioeducativos, os integrantes dos órgãos de que tratam o inciso IV do caput do art. 51, o inciso XIII do caput do art. 52, o § 8º e os incisos I a VI do caput do art. 144 da Constituição Federal exercem atividades de risco e são servidores públicos essenciais ao funcionamento do Estado. *006868421242DC* Para verificar as assinaturas, acesse https://infoleg-autenticidade-assinatura.camara.leg.br/CD242124868600	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2441800
33	23	PEC	2024	2024-05-27 17:10:00	Acrescenta o §2º no Art. 4º da Constituição para acrescentar a integração dos países de língua portuguesa entre os princípios que regem as relações internacionais da República Federativa do Brasil.	Art. 1º O Art. 4º da Constituição passa a vigorar com as seguintes alterações: “Art. § 1° § 2º. A República Federativa do Brasil buscará a integração econômica, política, social e cultural com os demais países que adotam oficialmente a língua portuguesa, visando a formação de uma comunidade lusófona de nações.” Art. 2º Renumere-se o parágrafo único do Art. 4º para §1º. Art. 3º Esta Emenda Constitucional entra em vigor na data de sua publicação. JUSTIFICAÇÃO	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2429603
34	21	PEC	2024	2024-05-23 12:02:00	Altera o art. 198 da Constituição Federal, para promover o enquadramento dos servidores públicos federais ocupantes do cargo de auxiliar de enfermagem para a carreira dos técnicos de enfermagem.	Art. 1º O art. 198 da Constituição Federal passa a vigorar acrescido dos §§ 16, 17 e 18: “Art. 198. …………………………………………………………… § 16. Mediante requerimento do interessado, a União promoverá o enquadramento dos servidores públicos federais ocupantes do cargo de auxiliar de enfermagem para a carreira de técnicos de enfermagem, desde que possuidores do diploma de técnico de enfermagem. § 17. Para fins de certificação, a União deverá emitir declarações sobre as atividades realizadas pelos auxiliares de enfermagem e	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2428589
35	20	PEC	2024	2024-05-21 14:17:00	Institui o Regime Extraordinário Fiscal, Financeiro e de Contratações destinado ao enfrentamento de calamidade pública e à reconstrução da infraestrutura física e social no Estado do Rio Grande do Sul, bem como ao suporte direto às famílias afetadas.	Art. 1º Durante a vigência de estado de calamidade pública no estado do Rio Grande do Sul, reconhecido pela Portaria nº 1.354, de 2 de maio de 2024 e Decreto Estadual nº 57.596, de 01 de maio de 2024, em decorrência de chuvas intensas, a União adotará Regime Extraordinário Fiscal, Financeiro e de Contratações para atender às necessidades dela decorrentes, somente naquilo em que a urgência for incompatível com o regime regular. Art. 2º Com o propósito exclusivo de enfrentamento do contexto da calamidade e de seus efeitos sociais e econômicos, no seu período de duração, o Poder Executivo Federal, no âmbito de suas competências, poderá adotar processos simplificados de contratação de pessoal, em caráter	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2426567
36	17	PEC	2024	2024-05-13 12:01:00	Acrescenta art. 132-A e altera o art. 168 da Constituição Federal, para conferir autonomia orçamentária às Procuradorias dos Estados e do Distrito Federal e à Advocacia-Geral da União e seus órgãos vinculados.	Art. 1º Fica acrescentado o seguinte art. 132-A à Constituição Federal: “Art. 132-A. À Advocacia-Geral da União, seus órgãos vinculados, e às Procuradorias-Gerais dos Estados e do Distrito Federal, integrados pelos Advogados e Procuradores de que tratam os artigos 131 e 132 desta Constituição, são asseguradas autonomia administrativa, técnica e orçamentária, dentro dos limites estabelecidos na Lei de Diretrizes Orçamentárias.” (NR) Art. 2º O art. 168 da Constituição Federal passa a vigorar com a seguinte redação: “Art. 168. Os recursos correspondentes às dotações orçamentárias, compreendidos os créditos suplementares e especiais, destinados aos	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2422264
37	14	PEC	2024	2024-04-19 09:32:00	Altera o art. 6º da Constituição Federal, para positivar o direito aos cuidados no rol de direitos sociais.	Art. 1º Esta Lei altera o art. 6º da Constituição Federal, para positivar o direito aos cuidados no rol de direitos sociais. Art. 2º O art. 6º da Constituição Federal passa a vigorar com a seguinte redação: “Art. 6º São direitos sociais a educação, a saúde, a alimentação, o trabalho, a moradia, o transporte, o lazer, a segurança, o cuidado, a previdência social, a proteção à maternidade e à infância, a assistência aos desamparados, na forma desta Constituição.” (NR) Art. 3º Esta emenda constitucional entra em vigor na data de	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2410715
38	6	PEC	2024	2024-03-05 16:42:00	Altera o inciso X do § 22 e insere o § 21-A no art. 40 da Constituição, altera o art. 11 da Emenda Constitucional nº 103, de 12 de novembro de 2019 e revoga os §§ 1º-A, 1º-B e 1º-C do art. 149 da Constituição e o § 8º do art. 9º da Emenda Constitucional nº 103, de 2019.	Art. 1º O inciso X do § 22 do art. 40 da Constituição Federal passa a vigorar com a seguinte redação: “Art. 40. § 22 Vedada a instituição de novos regimes próprios de previdência social, lei complementar federal estabelecerá, para os que já existem, normas gerais de organização, de funcionamento e de responsabilidade em sua gestção, dispondo, entre outros aspectos, sobre: X – parâmetros para apuração da base de cálculo e definição	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2391443
39	1286	MPV	2024	2024-12-31 00:00:00	Cria a Carreira de Desenvolvimento Socioeconômico, a Carreira de Desenvolvimento das Políticas de Justiça e Defesa e a Carreira de Fiscalização da Comissão de Valores Mobiliários, altera a remuneração de servidores e empregados públicos do Poder Executivo federal, altera a remuneração de cargos em comissão, de funções de confiança e de gratificações do Poder Executivo federal, reestrutura cargos efetivos, planos de cargos e carreiras, padroniza e unifica regras de incorporação de gratificações de desempenho, altera as regras do Sistema de Desenvolvimento na Carreira, transforma cargos efetivos vagos em outros cargos efetivos, em cargos em comissão e em funções de confiança, altera a regra de designação dos membros dos conselhos deliberativos e fiscais das entidades fechadas de previdência complementar e dá outras providências.	Art. 1º Esta Medida Provisória: I - cria a Carreira de Desenvolvimento Socioeconômico, a Carreira de Desenvolvimento das Políticas de Justiça e Defesa e a Carreira de Fiscalização da Comissão de Valores Mobiliários; II - altera a remuneração de servidores e empregados públicos do Poder Executivo federal; III - altera a remuneração de cargos em comissão, de funções de confiança e de gratificações do Poder Executivo federal; IV - reestrutura cargos efetivos, planos de cargos e carreiras; V - padroniza e unifica regras de incorporação de gratificações de desempenho;	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2848985
40	1285	MPV	2024	2024-12-29 00:00:00	Abre crédito extraordinário, em favor do Ministério da Pesca e Aquicultura, no valor de R$ 553.261.047,00, para o fim que especifica.	Art. 1º Fica aberto crédito extraordinário, em favor do Ministério da Pesca e Aquicultura, no valor de R$ 553.261.047,00 (quinhentos e cinquenta e três milhões duzentos e sessenta e um mil e quarenta e sete reais), para atender à programação constante do Anexo. Art. 2º Esta Medida Provisória entra em vigor na data de sua publicação. Brasília, 28 de dezembro de 2024; 203º da Independência e 136º da República. 1	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2848984
41	1284	MPV	2024	2024-12-29 00:00:00	Abre crédito extraordinário, em favor dos Ministérios do Desenvolvimento, Indústria, Comércio e Serviços; do Desenvolvimento Agrário e Agricultura Familiar; da Integração e do Desenvolvimento Regional; do Desenvolvimento e Assistência Social, Família e Combate à Fome; e das Cidades; e de Operações Oficiais de Crédito, no valor de R$ 357.443.320,00, para os fins que especifica.	Art. 1º Fica aberto crédito extraordinário, em favor dos Ministérios do Desenvolvimento, Indústria, Comércio e Serviços; do Desenvolvimento Agrário e Agricultura Familiar; da Integração e do Desenvolvimento Regional; do Desenvolvimento e Assistência Social, Família e Combate à Fome; e das Cidades; e de Operações Oficiais de Crédito, no valor de R$ 357.443.320,00 (trezentos e cinquenta e sete milhões quatrocentos e quarenta e três mil trezentos e vinte reais), para atender às programações constantes do Anexo. Art. 2º Esta Medida Provisória entra em vigor na data de sua publicação. Brasília, 28 de dezembro de 2024; 203º da Independência e 136º da República. 1	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2848983
42	1283	MPV	2024	2024-12-29 00:00:00	Abre crédito extraordinário, em favor do Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome, no valor de R$ 168.268.040,00, para os fins que especifica.	Art. 1º Fica aberto crédito extraordinário, em favor do Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome, no valor de R$ 168.268.040,00 (cento e sessenta e oito milhões duzentos e sessenta e oito mil e quarenta reais), para atender às programações constantes do Anexo. Art. 2º Esta Medida Provisória entra em vigor na data de sua publicação. Brasília, 28 de dezembro de 2024; 203º da Independência e 136º da República. 1	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2848982
43	1282	MPV	2024	2024-12-24 00:00:00	Abre crédito extraordinário, em favor do Ministério das Cidades, no valor de R$ 6.500.000.000,00, para o fim que especifica.	Art. 1º Fica aberto crédito extraordinário, em favor do Ministério das Cidades, no valor de R$ 6.500.000.000,00 (seis bilhões e quinhentos milhões de reais), para atender à programação constante do Anexo. Art. 2º Esta Medida Provisória entra em vigor na data de sua publicação. Brasília, 23 de dezembro de 2024; 203º da Independência e 136º da República. MP-CRÉD EXTRA MCIDADES R$ 6.500.000.000,00 (EM 118 MPO) 1	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2848981
44	1281	MPV	2024	2024-12-24 00:00:00	Abre crédito extraordinário, em favor dos Ministérios de Minas e Energia, do Meio Ambiente e Mudança do Clima, e de Portos e Aeroportos, no valor de R$ 233.200.194,00, para os fins que especifica.	Art. 1º Fica aberto crédito extraordinário, em favor dos Ministérios de Minas e Energia, do Meio Ambiente e Mudança do Clima, e de Portos e Aeroportos, no valor de R$ 233.200.194,00 (duzentos e trinta e três milhões duzentos mil cento e noventa e quatro reais), para atender às programações constantes do Anexo. Art. 2º Esta Medida Provisória entra em vigor na data de sua publicação. Brasília, 23 de dezembro de 2024; 203º da Independência e 136º da República. 1	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2848980
45	1280	MPV	2024	2024-12-17 00:00:00	Prorroga o prazo para utilização do Regime Especial de Tributação para Desenvolvimento da Atividade de Exibição Cinematográfica - Recine, constante da Lei nº 13.594, de 5 de janeiro de 2018, e os benefícios fiscais previstos no art. 44 da Medida Provisória nº 2.228-1, de 6 de setembro de 2001, e nos art. 1º e art. 1º-A da Lei nº 8.685, de 20 de julho de 1993.	Art. 1º A Lei nº 13.594, de 5 de janeiro de 2018, passa a vigorar com as seguintes alterações: “Art. 1º O benefício fiscal de que trata o art. 14 da Lei nº 12.599, de 23 de março de 2012, poderá ser utilizado até 31 de dezembro de 2029. § 2º Para os anos de 2018 a 2029, o benefício de que trata o caput fica limitado aos valores previstos nas respectivas leis orçamentárias anuais.” (NR) Art. 2º A Medida Provisória nº 2.228-1, de 6 de setembro de 2001, passa a vigorar com as seguintes alterações: “Art. 44. Até o período de apuração relativo ao ano-calendário de 2029,	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2848979
46	1279	MPV	2024	2024-12-17 00:00:00	Abre crédito extraordinário, em favor do Ministério da Integração e do Desenvolvimento Regional, no valor de R$ 120.000.000,00, para o fim que especifica.	Art. 1º Fica aberto crédito extraordinário, em favor do Ministério da Integração e do Desenvolvimento Regional, no valor de R$ 120.000.000,00 (cento e vinte milhões de reais), para atender à programação constante do Anexo. Art. 2º Esta Medida Provisória entra em vigor na data de sua publicação. Brasília, 16 de dezembro de 2024; 203º da Independência e 136º da República. 1	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2848978
47	1278	MPV	2024	2024-12-12 00:00:00	Autoriza a União a participar de fundo que tenha por finalidade apoiar a requalificação e a recuperação de infraestruturas nas áreas afetadas por eventos climáticos extremos e apoiar empreendimentos de infraestrutura relacionados à mitigação e à adaptação às mudanças climáticas.	Art. 1º Fica a União autorizada a participar de fundo que, atendidos os requisitos fixados nesta Medida Provisória, tenha por finalidade apoiar a requalificação e a recuperação de infraestruturas nas áreas afetadas por eventos climáticos extremos e apoiar empreendimentos de infraestrutura relacionados à mitigação e à adaptação às mudanças climáticas. Art. 2º O fundo de que trata o art. 1º terá natureza privada e patrimônio próprio separado do patrimônio dos cotistas e da instituição administradora e será sujeito a direitos e obrigações próprios. § 1º O fundo de que trata o art. 1º poderá ser criado, administrado, gerido e representado judicial e extrajudicialmente pela Caixa Econômica Federal. § 2º Os bens e os direitos integrantes do patrimônio do fundo, seus frutos e	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2848977
48	1277	MPV	2024	2024-11-29 00:00:00	Institui o Auxílio Extraordinário destinado a pescadoras e pescadores profissionais artesanais beneficiários do Seguro-Desemprego do Pescador Artesanal - Seguro-Defeso cadastrados em Municípios da Região Norte.	Art. 1º Fica instituído o Auxílio Extraordinário destinado a pescadoras e pescadores profissionais artesanais beneficiários do Seguro-Desemprego do Pescador Artesanal – Seguro- Defeso, nos termos do disposto no art. 1º da Lei nº 10.779, de 25 de novembro de 2003, cadastrados nos Municípios da Região Norte em situação de emergência decorrente de seca ou estiagem reconhecida pelo Poder Executivo federal até a data de publicação desta Medida Provisória, que não foram contemplados pela Medida Provisória nº 1.263, de 7 de outubro de 2024. Art. 2º O Auxílio Extraordinário consiste no pagamento de parcela única no valor de R$ 2.824,00 (dois mil oitocentos e vinte e quatro reais), devido aos beneficiários de que trata o art. 1º que tiveram o benefício concedido até a data de publicação desta Medida Provisória	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2833831
49	1276	MPV	2024	2024-11-25 00:00:00	Altera a Lei nº 7.797, de 10 de julho de 1989, e a Lei nº 14.944, de 31 de julho de 2024, para dispor sobre medidas para prevenção e combate a incêndios florestais.	Art. 1º A Lei nº 7.797, de 10 de julho de 1989, passa a vigorar com as seguintes alterações: “Art. 2º III-A - recursos provenientes de emendas parlamentares; e ” (NR) “Art. 3º-A Os recursos financeiros do Fundo Nacional de Meio Ambiente poderão ser transferidos aos entes subnacionais, para conta específica, dispensada a celebração de convênio ou instrumento congênere, para financiar projetos de prevenção, preparação e combate a incêndios florestais, inclusive de	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2833829
50	1275	MPV	2024	2024-11-25 00:00:00	Abre crédito extraordinário, em favor da Defensoria Pública da União e dos Ministérios do Planejamento e Orçamento, e da Integração e do Desenvolvimento Regional, no valor de R$ 118.206.027,00, para os fins que especifica.	Art. 1º Fica aberto crédito extraordinário, em favor da Defensoria Pública da União e dos Ministérios do Planejamento e Orçamento, e da Integração e do Desenvolvimento Regional, no valor de R$ 118.206.027,00 (cento e dezoito milhões duzentos e seis mil e vinte e sete reais), para atender às programações constantes do Anexo. Art. 2º Esta Medida Provisória entra em vigor na data de sua publicação. Brasília, 22 de novembro de 2024; 203º da Independência e 136º da República. MP-CRÉD EXTRA R$ 118.206.027,00 DPU E OUTROS (EM 100 MPO) 1	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2833827
51	1274	MPV	2024	2024-11-22 00:00:00	Altera a Lei nº 14.399, de 8 de julho de 2022, que institui a Política Nacional Aldir Blanc de Fomento à Cultura.	Art. 1º A Lei nº 14.399, de 8 de julho de 2022, passa a vigorar com as seguintes alterações: “Art. 3º Parágrafo único. O princípio estabelecido no inciso V do caput deve ser implementado por meio de Plano de Aplicação dos Recursos (PAAR), de caráter anual ou plurianual, ouvida a sociedade civil, preferencialmente, por intermédio de seus representantes nos Conselhos de Cultura.” (NR) “Art. 6º A partir de 2023, a União entregará aos Estados, ao Distrito Federal e aos Municípios o valor total de R$ 15.000.000.000,00 (quinze bilhões de reais).	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2825400
52	1273	MPV	2024	2024-11-13 00:00:00	Altera a Lei nº 14.724, de 14 de novembro de 2023, para dispor sobre novo prazo de vigência do Programa de Enfrentamento à Fila da Previdência Social - PEFPS.	Art. 1º A Lei nº 14.724, de 14 de novembro de 2023, passa a vigorar com as seguintes alterações: “Art. 9º O PEFPS terá vigência até 31 dezembro de 2024. ” (NR) Art. 2º Fica revogado o parágrafo único do art. 9º da Lei nº 14.724, de 14 de novembro de 2023. Art. 3º Esta Medida Provisória entra em vigor na data de sua publicação. Brasília, 13 de novembro de 2024; 203º da Independência e 136º da República. MP-ALTERA LEI 14.724-2023 PRORROGA BÔNUS PEFPS 1	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2825399
53	1272	MPV	2024	2024-10-25 00:00:00	Autoriza o Poder Executivo federal a conceder subvenção econômica, sob a forma de desconto, em operações de crédito rural contratadas no período de 6 a 22 de setembro de 2024, dispõe sobre a comissão de que trata o art. 3º da Medida Provisória nº 1.247, de 31 de julho de 2024, e altera a Lei nº 8.427, de 27 de maio de 1992, e a Lei nº 14.981, de 20 de setembro de 2024.	Art. 1º Para fins de concessão da subvenção econômica, sob a forma de desconto para liquidação ou renegociação de parcelas de operações de crédito rural de custeio, de investimento e de industrialização, nos termos da Medida Provisória nº 1.247, de 31 de julho de 2024, será admitido o enquadramento das parcelas de operações de crédito rural contratadas com recursos controlados cujos empreendimentos financiados estejam localizados nos Municípios do Estado do Rio Grande do Sul com estado de calamidade pública ou situação de emergência decretado até 31 de julho de 2024, reconhecido pelo Poder Executivo federal até 30 de agosto de 2024. Art. 2º A comissão de que trata o art. 3º da Medida Provisória nº 1.247, de 31 de julho de 2024, poderá atuar como instância validadora dos pedidos de desconto solicitados por	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2634017
54	1271	MPV	2024	2024-10-25 00:00:00	Dispõe sobre as remessas internacionais realizadas por intermédio de empresas de comércio eletrônico e reduz a alíquota do Imposto de Importação incidente sobre medicamentos.	Art. 1º A empresa de comércio eletrônico que realizar remessas internacionais no âmbito do regime de tributação simplificada, instituído pelo Decreto-Lei nº 1.804, de 3 de setembro de 1980, deverá: I - prestar, no prazo estabelecido pela Secretaria Especial da Receita Federal do Brasil do Ministério da Fazenda, as informações necessárias ao registro da declaração de importação de remessa previamente à chegada do veículo transportador da remessa ao País; e II - repassar, direta ou indiretamente, os valores dos tributos federais e estaduais, que deverão ser cobrados do destinatário, para o responsável pelo registro da declaração de importação de remessa no sistema informatizado da Secretaria Especial da Receita Federal do Brasil destinado ao controle das remessas internacionais.	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2633993
55	1270	MPV	2024	2024-10-24 00:00:00	Abre crédito extraordinário, em favor do Ministério da Integração e do Desenvolvimento Regional, no valor de R$ 87.000.000,00, para o fim que especifica.	Art. 1º Fica aberto crédito extraordinário, em favor do Ministério da Integração e do Desenvolvimento Regional, no valor de R$ 87.000.000,00 (oitenta e sete milhões de reais), para atender à programação constante do Anexo. Art. 2º Esta Medida Provisória entra em vigor na data de sua publicação. Brasília, 23 de outubro de 2024; 203º da Independência e 136º da República. MP-CRÉD EXTRAORD MIDR R$ 87.000.000,00 1	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2633980
56	1269	MPV	2024	2024-10-23 00:00:00	Abre crédito extraordinário, em favor de Operações Oficiais de Crédito, no valor de R$ 5.000.000.000,00, para o fim que especifica.	Art. 1º Fica aberto crédito extraordinário, em favor de Operações Oficiais de Crédito, no valor de R$ 5.000.000.000,00 (cinco bilhões de reais), para atender à programação constante do Anexo. Art. 2º Esta Medida Provisória entra em vigor na data de sua publicação. Brasília, 22 de outubro de 2024; 203º da Independência e 136º da República. 1	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2633956
57	1268	MPV	2024	2024-10-23 00:00:00	Abre crédito extraordinário, em favor dos Ministérios da Justiça e Segurança Pública, da Saúde, do Meio Ambiente e Mudança do Clima, do Desenvolvimento Agrário e Agricultura Familiar, da Integração e do Desenvolvimento Regional, do Desenvolvimento e Assistência Social, Família e Combate à Fome, e da Pesca e Aquicultura, no valor de R$ 938.458.061,00, para os fins que especifica.	Art. 1º Fica aberto crédito extraordinário, em favor dos Ministérios da Justiça e Segurança Pública, da Saúde, do Meio Ambiente e Mudança do Clima, do Desenvolvimento Agrário e Agricultura Familiar, da Integração e do Desenvolvimento Regional, do Desenvolvimento e Assistência Social, Família e Combate à Fome, e da Pesca e Aquicultura, no valor de R$ 938.458.061,00 (novecentos e trinta e oito milhões quatrocentos e cinquenta e oito mil e sessenta e um reais), para atender às programações constantes do Anexo. Art. 2º Esta Medida Provisória entra em vigor na data de sua publicação. Brasília, 22 de outubro de 2024; 203º da Independência e 136º da República. MP-CRÉD EXTRA R$ 938.458.061,00 MJSP E OUTROS 1	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2633874
58	1267	MPV	2024	2024-10-19 00:00:00	Dispõe sobre operações do Programa Nacional de Apoio às Microempresas e Empresas de Pequeno Porte - Pronampe com beneficiários que tiveram prejuízos causados pela interrupção do fornecimento de energia elétrica na Região Metropolitana de São Paulo, Estado de São Paulo, no mês de outubro de 2024.	Art. 1º A Lei nº 13.999, de 18 de maio de 2020, passa a vigorar com as seguintes alterações: “Art. 6º-E Sem prejuízo do disposto no art. 6º, § 2º, desta Lei, os valores não utilizados para garantia de operações com recursos do FGO, assim como os valores recuperados, inclusive no caso de inadimplência, poderão ser utilizados, até o limite de R$ 150.000.000,00 (cento e cinquenta milhões de reais), para constituição de patrimônio segregado, com direitos e obrigações próprios, exclusivamente para a cobertura de operações contratadas até 31 de dezembro de 2024, no âmbito do Pronampe, com beneficiários que tiveram prejuízos causados pela interrupção do fornecimento de energia elétrica na Região Metropolitana de	https://www.camara.leg.br/proposicoesWeb/prop_mostrarintegra?codteor=2488993
\.


--
-- Name: proposicoes_legislativas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: kaua
--

SELECT pg_catalog.setval('public.proposicoes_legislativas_id_seq', 58, true);


--
-- Name: proposicoes_legislativas proposicoes_legislativas_pkey; Type: CONSTRAINT; Schema: public; Owner: kaua
--

ALTER TABLE ONLY public.proposicoes_legislativas
    ADD CONSTRAINT proposicoes_legislativas_pkey PRIMARY KEY (id);


--
-- Name: proposicoes_legislativas unico_proposicao; Type: CONSTRAINT; Schema: public; Owner: kaua
--

ALTER TABLE ONLY public.proposicoes_legislativas
    ADD CONSTRAINT unico_proposicao UNIQUE (tipo, numero, ano);


--
-- Name: idx_ano; Type: INDEX; Schema: public; Owner: kaua
--

CREATE INDEX idx_ano ON public.proposicoes_legislativas USING btree (ano);


--
-- Name: idx_data_apresentacao; Type: INDEX; Schema: public; Owner: kaua
--

CREATE INDEX idx_data_apresentacao ON public.proposicoes_legislativas USING btree (data_apresentacao DESC);


--
-- Name: idx_numero; Type: INDEX; Schema: public; Owner: kaua
--

CREATE INDEX idx_numero ON public.proposicoes_legislativas USING btree (numero);


--
-- Name: idx_tipo; Type: INDEX; Schema: public; Owner: kaua
--

CREATE INDEX idx_tipo ON public.proposicoes_legislativas USING btree (tipo);


--
-- PostgreSQL database dump complete
--

\unrestrict LYg8vaGjOChqHzzm3iHpjpbmzA8Ig1kN2KJjZAPNNBh6xpwIUAe73BLkpZ4AIWD

